### ISSUE TITLE
Error when make imagestack

### ISSUE THREAD

**Issue by jingliuvic** [s-gupta/rcnn-depth#10]
When I input 'make all' in the terminal as the READEME file. There was some errors(5), like:
src/Network.cpp:304:5: error: use of undeclared identifier 'close'
    close(sock)

**Comment by s-gupta** [comment]
Thanks for pointing this out. It works for me on ubuntu 12.04 but not on ubuntu 14.04. I pushed a fix to the https://github.com/s-gupta/rgbdutils repository. Can you do a git pull origin in the rgbdutils folded and try again?

**Comment by jingliuvic** [comment]
I've tried again. Actually, no error now.( I use OS X10.10.2).
However, there's something like this:
//Applications/MATLAB_R2014b.app//bin/mex matlab/joint_bilateral_mex.cpp CXX="g++" CXXFLAGS="\$CXXFLAGS  -Iinclude/ -fPIC " CXXLIBS="\$CXXLIBS lib/libImageStack.a" -output matlab/joint_bilateral_mex.mexa64
ʹ?? 'Xcode Clang++' ???롣
MEX ?ѳɹ???ɡ?

**Comment by s-gupta** [comment]
Hi Jing,

Unfortunately this is a platform specific compilation issue. I dont have access to a development environment on OS X and will not be able to help with it. The command here is essentially trying to compile a mex file with the image stack library that you just complied. Hope this helps.

Thanks,

**Comment by jingliuvic** [comment]
Things just goes well. That is not a big problem.
Thank you very much! O(∩_∩)O

**Comment by wangjiaod** [comment]
如果第一次编译错误需要make clean然后再make all
