### ISSUE TITLE
Issue with getImage

### ISSUE THREAD

**Issue by manav95** [s-gupta/rcnn-depth#14]
When I run the saveHHA function to get my depth images turned into an HHA encoding, I get the message that getImage function could not be found. I tried looking through all of your repos but I couldn't find the function. Where are you getting getImage from? I thought about replacing it with imread instead but that doesn't give the necessary depth matrices. Can you tell me where you found the function?

**Comment by s-gupta** [comment]
Please follow installation instructions [here](https://github.com/s-gupta/rcnn-depth#installation-instructions). `getImage` is part of the `nyu-hooks` [repository](https://github.com/s-gupta/nyu-hooks.git).
