### ISSUE TITLE
Failed download http://www.cs.berkeley.edu/~sgupta/eccv14/eccv14-external-data.tgz

### ISSUE THREAD

**Issue by Tarssy** [s-gupta/rcnn-depth#23]
I can't download eccv14-external-data.tgz 
When I use wget http://www.cs.berkeley.edu/~sgupta/eccv14/eccv14-external-data.tgz

It return:
ERROR 404：Not Found

**Comment by sajidullah** [comment]
copy the link of eccv14-external-data.tgz from README.it works

**Comment by s-gupta** [comment]
This may have been a temporary issue with the web server. I can successfully download it right now.
