### ISSUE TITLE
why can not extract the files?

### ISSUE THREAD

**Issue by yatou1991** [s-gupta/rcnn-depth#24]
@s-gupta  hallo,perfessor .I meet some problem,and need your help sincerely.when I  download the code,I can extract the files completly.I try on several computers,but it still does not work . I can not figure out it,could you help me?

and I still meet some other problem,is there lose some files?   in the file   "rcnn-depth-master/demo.m",
![111](https://cloud.githubusercontent.com/assets/20459416/17889722/4b0e43bc-6964-11e6-953a-344c237861e8.PNG)
 Whether the function file is not uploaded ？Need your help?How can I deal with this?

**Comment by s-gupta** [comment]
Did you follow installation instructions [here](https://github.com/s-gupta/rcnn-depth#installation-instructions)? These functions are available in [this repository](https://github.com/s-gupta/nyu-hooks).
