### ISSUE TITLE
Can't run demo() in matlab, getting invalid mex file error

### ISSUE THREAD

**Issue by alexgbelov** [s-gupta/rcnn-depth#4]
I followed the steps in this issue: https://github.com/s-gupta/rcnn-depth/issues/2, and got to running the demo() command. However, when I run it, I get the following output

> > demo();

runname =

release

   Time taken for computing ng at scale 1: 8.929.

   Time taken for computing ng at scale 2: 4.930.
Invalid MEX-file
'/home/belov/rcnn-depth/eccv14-code/structured-edges/private/edgesDetectMex.mexa64': dlopen:
cannot load any more object with static TLS

Error in edgesDetect (line 68)
  if(nargout<4), [E,inds] = edgesDetectMex(model,I,chnsReg,chnsSim);

Error in edgesDetect (line 46)
    if(nargout<4), [E1,~,inds{i}]=edgesDetect(I1,model,ng1);

Error in getAllCues (line 23)
    Es = edgesDetect(Iin, model, zeros([size(Iin(:,:,1)), 0]));

Error in detectEdge (line 17)
    cues = getAllCues(Iin, Din, C, colorModel, opts.rgbd3opts.vars, cacheFile);

Error in run_all (line 12)
  [E, Es, O] = detectEdge(I, D, [], C, model, sc, [], []);

Error in demo (line 6)
run_all(I, D, RD, C, out_file);

I looked up issues regarding static TLS errors, and they were caused by a bug that should have been fixed in the latest release (I am running R2014b).

**Comment by viviensu** [comment]
Hi@alexgbelov,
I go the same problem as your first problem. My matlab version is R2016a. I did no t find any valuable solution about this 'cannot load any more object with static TLS'.  Would you please give me some advises?

**Comment by alexgbelov** [comment]
Hello. I'm sorry, but it has been too long since I have worked on the project, and I am afraid I can't give you any advice. I wish you good luck in figuring out the issue.

**Comment by viviensu** [comment]
Thank you for your reply anyway. I think I'd better try other way to solve it.

**Comment by LiliMeng** [comment]
I have the same error with using Matlab 2016a

Time taken for computing ng at scale 1: 2.836.

   Time taken for computing ng at scale 2: 1.474.
Invalid MEX-file '/home/lci/PR2017/rcnn-depth/eccv14-code/structured-edges/private/edgesDetectMex.mexa64': dlopen: cannot
load any more object with static TLS

Error in edgesDetect (line 69)
  if(nargout<4), [E,inds] = edgesDetectMex(model,I,chnsReg,chnsSim);


Error in edgesDetect (line 47)
    if(nargout<4), [E1,~,inds{i}]=edgesDetect(I1,model,ng1);


Error in getAllCues (line 23)
    Es = edgesDetect(Iin, model, zeros([size(Iin(:,:,1)), 0]));

Error in detectEdge (line 17)
    cues = getAllCues(Iin, Din, C, colorModel, opts.rgbd3opts.vars, cacheFile);

Error in run_all (line 12)
  [E, Es, O] = detectEdge(I, D, [], C, model, sc, [], []);

Error in demo (line 7)
run_all(I, D, RD, C, out_file);

**Comment by viviensu** [comment]
你好，看您的名字应该是中国人，所以方便起见，我们就用中文交流好了~这个问题我查遍了网上的资料，最后的答案是，这是Mathworks自己的问题，并且他们貌似没有要解决这个问题的想法。现在我们要想运行这个demo，唯一的方式就是更换matlab的版本，2014似乎是可用的。谢谢。不过对于我来说，我只是用到这个程度当中的一小部分，而这一部分和TLS错误没关系，所以我就比较幸运一点，直接禁止了TLS错误发生的部分。虽然没有什么建设性的意见，但还是希望能够帮到你，谢谢你的邮件~



wensu09@sina.cn
 
From: LiliMeng
Date: 2016-11-26 11:31
To: s-gupta/rcnn-depth
CC: Wen Su; Comment
Subject: Re: [s-gupta/rcnn-depth] Can't run demo() in matlab, getting invalid mex file error (#4)
I have the same error with using Matlab 2016a
Time taken for computing ng at scale 1: 2.836.
Time taken for computing ng at scale 2: 1.474.
Invalid MEX-file '/home/lci/PR2017/rcnn-depth/eccv14-code/structured-edges/private/edgesDetectMex.mexa64': dlopen: cannot
load any more object with static TLS
Error in edgesDetect (line 69)
if(nargout<4), [E,inds] = edgesDetectMex(model,I,chnsReg,chnsSim);
Error in edgesDetect (line 47)
if(nargout<4), [E1,~,inds{i}]=edgesDetect(I1,model,ng1);
Error in getAllCues (line 23)
Es = edgesDetect(Iin, model, zeros([size(Iin(:,:,1)), 0]));
Error in detectEdge (line 17)
cues = getAllCues(Iin, Din, C, colorModel, opts.rgbd3opts.vars, cacheFile);
Error in run_all (line 12)
[E, Es, O] = detectEdge(I, D, [], C, model, sc, [], []);
Error in demo (line 7)
run_all(I, D, RD, C, out_file);
―

**Comment by vinodkkurmi** [comment]
@s-gupta   I am getting following error . I am using R2012b.

>> demo()

runname =

release

    17


   Time taken for computing ng at scale 1: 3.421.

   Time taken for computing ng at scale 2: 2.147.
Undefined function 'edgesDetectMex' for input arguments of type 'struct'.

Error in edgesDetect (line 69)
  if(nargout<4), [E,inds] = edgesDetectMex(model,I,chnsReg,chnsSim);

Error in edgesDetect (line 47)
    if(nargout<4), [E1,~,inds{i}]=edgesDetect(I1,model,ng1);

Error in getAllCues (line 23)
    Es = edgesDetect(Iin, model, zeros([size(Iin(:,:,1)), 0]));

Error in detectEdge (line 17)
    cues = getAllCues(Iin, Din, C, colorModel, opts.rgbd3opts.vars, cacheFile);

Error in run_all (line 12)
  [E, Es, O] = detectEdge(I, D, [], C, model, sc, [], []);

Error in demo (line 6)
run_all(I, D, RD, C, out_file);

What could be the possible reason for this. 

Thanks in advance
