### ISSUE TITLE
http request error during downloading NYUv2 dataset

### ISSUE THREAD

**Issue by kemangjaka** [s-gupta/rcnn-depth#46]
Hi, thank you so much for sharing the code!
When I tried to download data from 
http://www.cs.berkeley.edu/~sgupta/eccv14/eccv14-data.tgz ,
I cannot connect to the server. 
The same thing happened to the pretrained models. 

How can I solve it?
Thank you !

**Comment by s-gupta** [comment]
Sorry for the delay, I ave made the data available here:
https://www.dropbox.com/sh/zyewldvlivyhwwj/AAD0llrV-R-DfAmfbTzX6I2ua?dl=0

Let me know if you need anything else.

**Comment by kemangjaka** [comment]
Hi, thank you for the reply!
I could download the data from the URL!

Thank you so much, and closing the issue.
