### ISSUE TITLE
Error running demo - unable to recognize joint_bilateral_mex

### ISSUE THREAD

**Issue by jananig** [s-gupta/rcnn-depth#5]
I tried to run demo in matlab after follwing the directions in the readme (building toolboxes, mcg, rcnn) and get the following error:

runname =

release

Undefined function 'joint_bilateral_mex' for
input arguments of type 'single'.

Error in jointBilateral (line 16)
  aa = joint_bilateral_mex(single(II),
  single(refII), sigma1, sigma2);

Error in computeNormals>filterItChopOffIS (line
65)
	fFilt = jointBilateral(sp, f, 1, 1000);

Error in computeNormals (line 34)
	AtA = filterItChopOffIS(cat(3, AtARaw,
        AtbRaw), superpixels, disparity,
        sigmaSupport, sigmaSuperpixel,
        sigmaDisparity);

Error in wrapperComputeNormals (line 39)
	[N b] = computeNormals(X, Y, Z,
        disparity, missingMask, superpixels,
        sigmaSupport, sigmaDisparity,
        sigmaSuperpixel);
Error in yCues (line 11)
  [N, b, pc] =
  wrapperComputeNormals(double(D)./100,
  false(size(D)), 3, s, C);

Error in getAllCues (line 12)
    [y1, y2, y3, angl1, angl2] = yCues(D, C, 1);

Error in detectEdge (line 17)
    cues = getAllCues(Iin, Din, C, colorModel,
    opts.rgbd3opts.vars, cacheFile);

Error in run_all (line 12)
  [E, Es, O] = detectEdge(I, D, [], C, model,
  sc, [], []);

Error in demo (line 6)
run_all(I, D, RD, C, out_file);

**Comment by ljhp** [comment]
I tried to run demo in matlab(Win7),there  is a error :C = cropCamera(getCameraParam('color')),Undefined function 'getCameraParam' for input arguments
of type 'char';Could you help me ? and  which part is tell  "geocentric embedding for depth images" Thx!!

**Comment by s-gupta** [comment]
Did you follow the installation instructions and also checkout the nyu hooks from here: https://github.com/s-gupta/nyu-hooks ? This function is a part of nyu hooks.
