### ISSUE TITLE
Not enough input arguments in EdgesDemo

### ISSUE THREAD

**Issue by DaddyWesker** [s-gupta/rcnn-depth#8]
Hello,

Tried to launch demo. The next error has appeared. 

"Error using edgesDetect (line 61)
Not enough input arguments.

Error in edgesDemo (line 25)
tic, E=edgesDetect(I,model); toc"

So, edgesDetect which you use in edgesDemo requires 3 arguments "I,model, ng", and in edgesDemo this function called with only 2 arguments "tic, E=edgesDetect(I,model); toc". What have to be in place of "ng", third input?

Thank you in advance.

**Comment by s-gupta** [comment]
edgesDemo is a demo function for the Structured Edges toolbox. Please look at run_all.m for how to run our RGB-D edge detector and look at scripts/script_edges.m for how to train the RGB-D edge detector.
