### ISSUE TITLE
Problems when follow the ReadMe and Checkout

### ISSUE THREAD

**Issue by jingliuvic** [s-gupta/rcnn-depth#9]
when I use 'git checkout e5cc609138a0bc4ce5177a67cf84952756d11b38' as the ReadMe.md indicates, I'm notified that  "You are in 'detached HEAD' state.". Is that just Ok?

**Comment by s-gupta** [comment]
Yes, this is fine. This is only to check out the version of caffe that was used to develop and test the rcnn-depth code base. Caffe has changed since, and I have not tested this code base with the latest release.

**Comment by danielruelle** [comment]
When I checkout, it shows:
"fatal: reference is not  a tree: e5cc609138a0bc4ce5177a67cf84952756d11b38"
Please help to indicate which release do you use for rcnn-depth among these https://github.com/BVLC/caffe/releases

Thanks

**Comment by s-gupta** [comment]
I just checked, I dont see such an error, and `git checkout e5cc609138a0bc4ce5177a67cf84952756d11b38` seems to work for me.

**Comment by ahundt** [comment]
I can confirm that version is present in the main caffe tree:
https://github.com/BVLC/caffe/commit/e5cc609138a0bc4ce5177a67cf84952756d11b38
